import { Breadcrumbs } from "@/components/Breadcrumbs";
import { SEO } from "@/components/SEO";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AnimatedCounter } from "@/components/AnimatedCounter";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Link } from "wouter";
import { motion } from "framer-motion";
import { Star, TrendingUp, Shield, Award, CheckCircle2, XCircle } from "lucide-react";

export default function ResultsPage() {
  const stats = [
    {
      icon: <TrendingUp className="w-8 h-8 text-primary" />,
      value: "20+",
      label: "The Floor",
      description: "Guaranteed SQOs/SDR/mo. Locked in at Month 5.",
    },
    {
      icon: <Award className="w-8 h-8 text-primary" />,
      value: "80+",
      label: "The Ceiling",
      description: "Sustained SQOs/mo generated by a single 2-SDR Pod.",
    },
    {
      icon: <Shield className="w-8 h-8 text-primary" />,
      value: "0%",
      label: "The Asset",
      description: "Pipeline Risk. If an operator leaves, the system remains.",
    },
  ];

  const caseStudies = [
    {
      id: "case-1",
      title: 'The "80-Meeting Pod"',
      industry: "B2B SaaS",
      model: "Series B",
      plan: "2-SDR Pod",
      challenge: "Complex ICP, needed to scale pipeline faster than 40-SQO guarantee",
      solution: "Deployed 2-SDR Pod ($15k/mo). After 8 months, operators running perfected Impact Selling OS became so efficient they doubled quota twice, generating sustained 80-90 qualified meetings per month.",
      result: "40-SQO guarantee was floor; 80+ became new reality. Value of investing in an asset.",
      stats: [
        { label: "Investment", value: "$15k/mo" },
        { label: "Time to Excellence", value: "8 months" },
        { label: "Monthly SQOs", value: "80-90" },
      ],
    },
    {
      id: "case-2",
      title: "How Client Y Escaped the '$198,000 Liability'",
      industry: "FinTech",
      model: "Series A",
      plan: "1-SDR Engine",
      challenge: "Hired and fired two internal SDRs in 12 months, burning over $200k with zero pipeline. Lone Wolf model was Single Point of Failure that kept failing.",
      solution: "Deployed 1-SDR Fullstack Sales Unit ($12.5k/mo). Completed 4-month ramp, Month 5 had guaranteed 20+ SQOs/mo.",
      result: "For less than cost of one failed hire, built permanent guaranteed pipeline asset. First year delivered 240+ qualified meetings. Pipeline now predictable, reliable, and safe.",
      stats: [
        { label: "Previous Loss", value: "$200k+" },
        { label: "New Investment", value: "$12.5k/mo" },
        { label: "First Year SQOs", value: "240+" },
      ],
    },
  ];

  const testimonials = [
    {
      quote: "The 2-SDR Pod is a no-brainer. We get 40+ guaranteed meetings a month for $15k. My last single internal hire cost me $16k a month all-in and produced 5 meetings. The math is undeniable.",
      name: "Michael Chen",
      title: "CRO",
      company: "TechVenture Inc",
      rating: 5,
    },
    {
      quote: "The reliability is everything. We had an internal rep quit, and it nearly killed our quarter. With Revenue Party, our operator left for a new role, and they slotted in a new one. The 'system' kept working, and our pipeline didn't even notice. That peace of mind is the real ROI.",
      name: "Sarah Martinez",
      title: "Head of Sales",
      company: "Growth Systems",
      rating: 5,
    },
    {
      quote: "We chose Revenue Party over Belkins because we wanted to own the asset. The 'Zero-IP Trap' was our biggest fear. We now have a complete, documented 'Impact Selling OS' that we own. It's our asset, not theirs.",
      name: "David Thompson",
      title: "VP of Revenue",
      company: "ScaleUp Solutions",
      rating: 5,
    },
  ];

  return (
    <>
      <SEO 
        title="The Numbers Don't Lie. The Results Are Guaranteed. | Revenue Party"
        description="Revenue Party case studies: See guaranteed 20+ SQOs/SDR monthly floor, 80+ SQO ceiling, and 0% pipeline risk. Real outsourced SDR results from our GTM engine."
        keywords="Revenue Party case studies, outsourced SDR case study, GTM engine results, guaranteed sales appointments, SDR performance, sales system results"
        canonical="/results"
      />
      <Breadcrumbs items={[]} currentPage="Results & Case Studies" />
      
      <div className="min-h-screen">
        {/* Hero Module */}
        <section className="pt-32 pb-20 px-4 md:px-6 lg:px-8">
          <div className="max-w-7xl mx-auto">
            <div className="text-center max-w-4xl mx-auto space-y-6">
              <motion.h1
                className="text-5xl md:text-6xl lg:text-7xl font-bold leading-tight"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8 }}
                data-testid="heading-hero"
              >
                The Numbers Don't Lie.{" "}
                <span className="text-primary">The Results Are Guaranteed.</span>
              </motion.h1>
              <motion.p
                className="text-xl md:text-2xl text-muted-foreground leading-relaxed"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.2 }}
                data-testid="text-hero-subheading"
              >
                We provide a guaranteed performance 'floor' and an asset-driven 'ceiling' with massive upside.
              </motion.p>
            </div>
          </div>
        </section>

        {/* At-a-Glance "Proven Results" Module */}
        <section className="py-20 px-4 md:px-6 lg:px-8 bg-card/30" data-testid="section-proven-results">
          <div className="max-w-7xl mx-auto">
            <div className="text-center max-w-3xl mx-auto mb-16">
              <h2 className="text-4xl md:text-5xl font-bold mb-6" data-testid="heading-proven-results">
                The 'Fullstack Sales Unit':{" "}
                <span className="text-primary">Verified Performance</span>
              </h2>
              <p className="text-xl text-muted-foreground leading-relaxed" data-testid="text-proven-results-description">
                Our model is designed for three outcomes: Guaranteed Results, Total Reliability, and a Permanent Asset.
              </p>
            </div>

            <div className="grid md:grid-cols-3 gap-8">
              {stats.map((stat, index) => (
                <motion.div
                  key={stat.label}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-50px" }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                >
                  <Card className="p-8 hover-elevate transition-all h-full text-center" data-testid={`card-stat-${index + 1}`}>
                    <div className="flex justify-center mb-4">
                      {stat.icon}
                    </div>
                    <AnimatedCounter
                      value={stat.value}
                      className="text-6xl font-bold text-primary mb-4"
                    />
                    <h3 className="text-2xl font-bold mb-4">{stat.label}</h3>
                    <p className="text-muted-foreground leading-relaxed">
                      {stat.description}
                    </p>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Featured Case Studies Module */}
        <section className="py-20 px-4 md:px-6 lg:px-8" data-testid="section-case-studies">
          <div className="max-w-7xl mx-auto">
            <div className="text-center max-w-3xl mx-auto mb-16">
              <h2 className="text-4xl md:text-5xl font-bold mb-6" data-testid="heading-case-studies">
                The Antidotes:{" "}
                <span className="text-primary">How We Fix the Traps</span>
              </h2>
              <p className="text-xl text-muted-foreground leading-relaxed" data-testid="text-case-studies-description">
                Our clients come to us from one of two failed models. Here's how we build their solution.
              </p>
            </div>

            <div className="space-y-8 max-w-5xl mx-auto">
              <Accordion type="single" collapsible className="space-y-6">
                {caseStudies.map((study, index) => (
                  <AccordionItem
                    key={study.id}
                    value={study.id}
                    className="border-none"
                  >
                    <Card className="overflow-hidden" data-testid={`card-case-study-${index + 1}`}>
                      <AccordionTrigger className="px-8 py-6 hover:no-underline hover-elevate [&[data-state=open]]:pb-4">
                        <div className="flex flex-col items-start text-left space-y-4 flex-1 pr-4">
                          <div className="flex flex-wrap gap-2">
                            <Badge variant="secondary" data-testid={`badge-industry-${index + 1}`}>
                              {study.industry}
                            </Badge>
                            <Badge variant="secondary" data-testid={`badge-model-${index + 1}`}>
                              {study.model}
                            </Badge>
                            <Badge variant="outline" data-testid={`badge-plan-${index + 1}`}>
                              {study.plan}
                            </Badge>
                          </div>
                          <h3 className="text-2xl font-bold" data-testid={`heading-case-study-${index + 1}`}>
                            {study.title}
                          </h3>
                        </div>
                      </AccordionTrigger>
                      <AccordionContent className="px-8 pb-8">
                        <div className="space-y-6 pt-4">
                          {/* Challenge */}
                          <div className="space-y-3">
                            <div className="flex items-start gap-3">
                              <XCircle className="w-5 h-5 text-destructive flex-shrink-0 mt-1" />
                              <div>
                                <h4 className="font-bold text-lg mb-2">Challenge</h4>
                                <p className="text-muted-foreground leading-relaxed" data-testid={`text-challenge-${index + 1}`}>
                                  {study.challenge}
                                </p>
                              </div>
                            </div>
                          </div>

                          {/* Solution */}
                          <div className="space-y-3">
                            <div className="flex items-start gap-3">
                              <CheckCircle2 className="w-5 h-5 text-primary flex-shrink-0 mt-1" />
                              <div>
                                <h4 className="font-bold text-lg mb-2">Solution</h4>
                                <p className="text-muted-foreground leading-relaxed" data-testid={`text-solution-${index + 1}`}>
                                  {study.solution}
                                </p>
                              </div>
                            </div>
                          </div>

                          {/* Result */}
                          <div className="space-y-3">
                            <div className="flex items-start gap-3">
                              <Award className="w-5 h-5 text-primary flex-shrink-0 mt-1" />
                              <div>
                                <h4 className="font-bold text-lg mb-2">Result</h4>
                                <p className="text-muted-foreground leading-relaxed" data-testid={`text-result-${index + 1}`}>
                                  {study.result}
                                </p>
                              </div>
                            </div>
                          </div>

                          {/* Stats */}
                          <div className="grid grid-cols-3 gap-4 pt-4 border-t">
                            {study.stats.map((stat, statIndex) => (
                              <div key={statIndex} className="text-center" data-testid={`stat-${index + 1}-${statIndex + 1}`}>
                                <div className="text-2xl font-bold text-primary mb-1">
                                  {stat.value}
                                </div>
                                <div className="text-sm text-muted-foreground">
                                  {stat.label}
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      </AccordionContent>
                    </Card>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>
          </div>
        </section>

        {/* Testimonial Wall Module */}
        <section className="py-20 px-4 md:px-6 lg:px-8 bg-card/30" data-testid="section-testimonials">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl md:text-5xl font-bold mb-6" data-testid="heading-testimonials">
                Don't Just Take{" "}
                <span className="text-primary">Our Word For It</span>
              </h2>
            </div>

            <div className="grid md:grid-cols-3 gap-8">
              {testimonials.map((testimonial, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-50px" }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                >
                  <Card className="p-8 hover-elevate transition-all h-full flex flex-col" data-testid={`card-testimonial-${index + 1}`}>
                    {/* Star Rating */}
                    <div className="flex gap-1 mb-6" data-testid={`stars-testimonial-${index + 1}`}>
                      {Array.from({ length: testimonial.rating }).map((_, i) => (
                        <Star
                          key={i}
                          className="w-5 h-5 fill-primary text-primary"
                        />
                      ))}
                    </div>

                    {/* Quote */}
                    <blockquote className="text-muted-foreground leading-relaxed mb-6 flex-1" data-testid={`quote-testimonial-${index + 1}`}>
                      "{testimonial.quote}"
                    </blockquote>

                    {/* Attribution */}
                    <div className="border-t pt-4" data-testid={`attribution-testimonial-${index + 1}`}>
                      <div className="font-bold">{testimonial.name}</div>
                      <div className="text-sm text-muted-foreground">
                        {testimonial.title}, {testimonial.company}
                      </div>
                    </div>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Primary CTA Module */}
        <section className="py-20 px-4 md:px-6 lg:px-8" data-testid="section-cta">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-4xl md:text-5xl font-bold mb-6" data-testid="heading-cta">
              Ready to Build Your Own{" "}
              <span className="text-primary">Guaranteed Asset?</span>
            </h2>
            <p className="text-xl text-muted-foreground mb-8 leading-relaxed" data-testid="text-cta-description">
              Stop renting activity and start building your engine. Schedule a free GTM Audit to get your custom blueprint.
            </p>
            <Button size="lg" className="text-lg px-8 py-6 shadow-lg" data-testid="button-cta-schedule" asChild>
              <Link href="/audit">Schedule My GTM Audit</Link>
            </Button>
          </div>
        </section>
      </div>
    </>
  );
}
